workflows:
  expo-android:
    name: Alwaleed App APK
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: | 
          npm install
      - name: Clean and Prebuild
        script: |
          # حذف أي مخلفات قديمة لضمان بناء نظيف
          rm -rf android
          npx expo prebuild --platform android --no-install
      - name: Build Android APK
        script: |
          cd android
          # أمر التنظيف الداخلي للأندرويد قبل البناء
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
